filter:
    excluded_paths: [.idea/*, doc/*, examples/*, tests/*]

checks:
    php: true

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: 'tests/coverage.clover'
                    format: 'clover'
